### ISSUE TITLE
如何生成elastic-job-lite-console-${version}.tar.gz压缩包

### ISSUE THREAD

**Issue by yongqianghou** [dangdangdotcom/elastic-job#363]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.4
### Expected behavior
 ”使用指南> 运维平台“中存在”解压缩elastic-job-lite-console-${version}.tar.gz并执行bin\start.sh”这段话；如何下载或者生成elastic-job-lite-console-${version}.tar.gz
### Actual behavior
希望提供一个elastic-job-lite-console-${version}.tar.gz下载链接或者生成该压缩包指南

**Comment by terrymanu** [comment]
文档里面有写，通过mvn install编译获取。
http://dangdangdotcom.github.io/elastic-job/elastic-job-lite/02-guide/web-console/

**Comment by yongqianghou** [comment]
Thank you very much!

**Comment by edisontest** [comment]
你好，今天我pull了代码，使用mvn install 安装了elatis-job-lite-console-2.1.5将获得的tar.gz文件上传到linux上解压缩后，发现问题问题如下：
1》执行bin/start.sh 出现错误bash: ./a.sh: /bin/bash^M: bad interpreter: No such file or directory
   之后使用vi编辑start.sh进入末行模式:set ff发现fileformat=dos，之后改成:set fileformat=unix  最后保存。此错误不再出现。
2》执行bin/start.sh 发现如下主要的错误信息：Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.model.core.LeafInfo
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
不知道是否是我install的时候出错了？我本地的环境是jdk1.8。修改java.version后执行mvn install也是这个错误。不知道怎么改？
